### PR TITLE
84 handle per event errors

### LINKED ISSUE #84: Handle per event errors
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description

Currently the sink connector doesn't process the returned response from the batch writes.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

There is old code using  `org.json` classes that wraps up the results, but they never get used by the caller 
https://github.com/IBM/cloudant-kafka-connector/blob/947c8d6a27b02908f9a1c51749660e24dd040cf3/src/main/java/com/ibm/cloudant/kafka/connect/CloudantSinkTask.java#L106

The wrapping of the response also happens to be the only place that still uses `org.json` dependency.

We should remove the `org.json` wrapping and dependency.
Instead return a list of errors that can be used by the sink connector to indicate an error with a specific event record.

### 2. What you expected to happen

per event errors logged somewhere

### 3. What actually happened

errors ignored

### PR DESCRIPTION
**Pull request by tomblench**
Handle errors in sink connector arising from posting to bulk_docs endpoint:

- Individual errors in batch response are reported to the error reporter, if present. This allows the original events to be sent to a DLQ and/or logged according to standard kafka config
- For more serious network/HTTP errors, throw an exception. This will ensure that the offsets are not committed and the event can be retried.

Additionally:
- Break up calls to bulk_docs into batches to avoid large request bodies
- Add tests for error handling

Fixes #84

### CODE REVIEW

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java [hunk 1]
```diff
@@ -123,4 +167,10 @@ public void close(Collection<TopicPartition> partitions) {
 		LOG.info("Committed ");
 	}
 
+	// for testing
+	// TODO find out if there is a better way to do this without changing production classes
+	public void setContext(SinkTaskContext ctx) {
+		this.context = ctx;
+	}
```
Comment (ricellis) [inline src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java:174]: The `SinkTask` API appears to offer [`initialize(SinkTaskContext)`](https://kafka.apache.org/31/javadoc/org/apache/kafka/connect/sink/SinkTask.html#initialize(org.apache.kafka.connect.sink.SinkTaskContext))

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java [hunk 2]
```diff
@@ -101,13 +107,51 @@ public void start(Map<String, String> props) {
...
+						reporter.report(r, re);
+					}
+				}
+			} else {
+				throw new ConnectException("Exception thrown when trying to write documents", re);
+			}
 		} finally {
-			// Release memory (regardless if documents got committed or not)
-			jsonArray = new LinkedList<>();
+			accumulatedSinkRecords = null;
```
Comment (ricellis) [inline src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java:154]: I'm a little uneasy about this, what if we only processed half the list when an exception occurs, won't we "lose" the accumulated records? I think ultimately it will depend on whether the offsets for those records have been committed.

AIUI the offsets are "commited" after `put` is called, but further reading suggests that they are just committed on a cron, and `put` throwing an exception is used to determine what is [not] eligible and needs retrying. Now that we are not writing during `put` we may want to be a more careful about the offsets. For example, a 60 second commit timer seems inappropriate if it takes us 2 minutes to write a batch, because we'd commit offsets before we actually wrote the records.

I think we may need to override `preCommit` and have it "replace" `flush`, but return the record offsets that we've actually processed so Kafka knows what is eligible to commit. [This](https://stackoverflow.com/a/45202162) seems to be helpful information on this topic.

File: src/main/java/com/ibm/cloud/cloudant/kafka/common/utils/JavaCloudantUtil.java [hunk 3]
```diff
@@ -61,56 +56,25 @@ public class JavaCloudantUtil {
...
-		} catch (Exception e) {
-			LOG.error("Exception caught in batchWrite()", e);
-			if(e.getMessage().equals(String.format(ResourceBundleUtil.get(
-				MessageKey.CLOUDANT_LIMITATION)))){
-				// try to put items from jsonResult before exception occurred
-				result.put(jsonResult);
-			}
-		}
-		return result;
+		// caller's responsibility to catch RuntimeException on execute() if thrown
```
Comment (ricellis) [inline src/main/java/com/ibm/cloud/cloudant/kafka/common/utils/JavaCloudantUtil.java:75]: Ofc this is a `RuntimeException`, but can we declare it on the method signature anyway and javadoc it so that someone adding new code in future has a better chance to see it is expected to be handled.

**Review by ricellis — COMMENTED** [review]
Some initial thoughts (note I haven't reviewed the test code).

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java [hunk 4]
```diff
@@ -101,13 +107,51 @@ public void start(Map<String, String> props) {
...
 		try {
-				JavaCloudantUtil.batchWrite(config.originalsStrings(), jsonArray);
-				LOG.info("Committed " + jsonArray.size() + " documents to -> " + config.getString(InterfaceConst.URL));
+			LOG.info(String.format("Calling batchWrite with %d documents to %s", jsonArray.size(), config.getString(InterfaceConst.URL)));
+			List<DocumentResult> writeResults = JavaCloudantUtil.batchWrite(config.originalsStrings(), jsonArray);
+			boolean ok = writeResults.stream().allMatch(DocumentResult::isOk);
+			if (!ok) {
+				LOG.error("Failed to write some documents");
+				for (int i=0; i<writeResults.size(); i++) {
+					// TODO - is checking isOk sufficient?
```
[the remark this answers is not in the document]
Comment (tomblench) [reply src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java:133]: But is there anything we can usefully do with `error` or `reason` other than log them? By sending the sink records to the reporter, they will by placed on any DLQ (if configured), but that's about all we can do.

[the remark this answers is not in the document]
Comment (ricellis) [reply src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java:133]: I think we want to "wrap" the `error`/`reason` in a `Throwable` (maybe `DataException`?) to pass to the `ErrantRecordReporter`. That way there will be some specific exception context associated with the particular message when reported. I think that error metadata can then make it into the log/DLQ as configured by the user (and we don't need to duplicate log it).

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java [hunk 5]
```diff
@@ -101,13 +107,51 @@ public void start(Map<String, String> props) {
...
 	public void flush(Map<TopicPartition, org.apache.kafka.clients.consumer.OffsetAndMetadata> offsets) {
-		LOG.debug("Flushing output stream for {" + config.getString(InterfaceConst.URL) + "}");
+
+		System.out.println(Arrays.toString(Thread.currentThread().getStackTrace()));
+
+		List<Map<String, Object>> jsonArray = new LinkedList<>();
+
+		if (accumulatedSinkRecords != null) {
+			// Note: _rev is preserved
+			accumulatedSinkRecords.stream()
```
[the remark this answers is not in the document]
Comment (tomblench) [reply src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java:108]: See my solution in b72b8d3 - I kept the stream and then just used an old-school loop combined with `subList` to break it down into batches.

As for synchronisation - it's not needed as everything is sequential. I checked the source code of [WorkerSinkTask](https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L211) - effectively each time `iteration` calls `commitOffsets` (which eventually calls our `preCommit` and `flush`) and then calls `poll` (which eventually calls `deliverMessages` and our `put`).

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java [hunk 6]
```diff
@@ -101,13 +107,51 @@ public void start(Map<String, String> props) {
...
+					});
+		}
+
+
 		try {
-				JavaCloudantUtil.batchWrite(config.originalsStrings(), jsonArray);
-				LOG.info("Committed " + jsonArray.size() + " documents to -> " + config.getString(InterfaceConst.URL));
+			LOG.info(String.format("Calling batchWrite with %d documents to %s", jsonArray.size(), config.getString(InterfaceConst.URL)));
+			List<DocumentResult> writeResults = JavaCloudantUtil.batchWrite(config.originalsStrings(), jsonArray);
+			boolean ok = writeResults.stream().allMatch(DocumentResult::isOk);
```
[the remark this answers is not in the document]
Comment (tomblench) [reply src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java]: Fixed in b72b8d3 - which is slightly more optimal and perhaps more logical.

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (tomblench) [reply src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java]: I've used `RuntimeException` in b72b8d3 for the sake of getting something working but I'm open-minded about using a more specific exception

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java (hunk 1 above)
Comment (tomblench) [reply src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java]: Thanks for spotting this - done in 6a8928b

File: src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java (hunk 2 above)
Comment (tomblench) [reply src/main/java/com/ibm/cloud/cloudant/kafka/connect/CloudantSinkTask.java]: I've stuck with overriding `flush` in 6a8928b , but the logic has changed to only clear the list if all was successful.

If we get an exception from batch write, then we re-throw it wrapped (this isn't necessary as the comments make clear, and if you think I should get rid of the wrapping, I'm happy to). This will ensure that the `accumulateSinkRecords` are re-tried the next time `flush` is called - I verified this by replacing the batch write with a stub which throws exceptions every time.

File: src/main/java/com/ibm/cloud/cloudant/kafka/common/utils/JavaCloudantUtil.java (hunk 3 above)
Comment (tomblench) [reply src/main/java/com/ibm/cloud/cloudant/kafka/common/utils/JavaCloudantUtil.java:75]: Was this already there on db31f55764e0d90d6358ef6974b624a4dd3b7ee2 ?

Comment (ricellis) [reply src/main/java/com/ibm/cloud/cloudant/kafka/common/utils/JavaCloudantUtil.java:75]: Oh yeah, sorry I missed it with the line break I think.

**Review by ricellis — COMMENTED** [review]
A few nits, but overall I think this is in good shape now.

**Review by ricellis — APPROVED** [review]
