### PR TITLE
fix: ensure sink task is partitioned properly

### LINKED ISSUE #104: Split topics and partitions across multiple sink tasks
Multiple topics and topic partitions should be broken down to separate tasks in the sink connector, at least up to the configured maxTasks.
This will leverage the maximum parallelism of Kafka in the conumption of events.

### PR DESCRIPTION
**Pull request by tomblench**
- Don't override SinkTask#open - if topics are partitioned and max.tasks > 1 then flush will be called with the correctly assigned partitions for each task
- Cleanup taskConfigs implementation in sink and source
- Remove max tasks and task number from task classes - they don't need to know this
- Remove task specific config classes - they're not needed

fixes #104

### CODE REVIEW

File: src/main/java/com/ibm/cloud/cloudant/kafka/schema/ConnectRecordMapper.java [hunk 1]
```diff
@@ -33,6 +33,9 @@
     private static Logger LOG = LoggerFactory.getLogger(ConnectRecordMapper.class);
 
     public Map<String, Object> apply(ConnectRecord<R> record) {
+        if (record.value() == null) {
```
Comment (tomblench) [inline src/main/java/com/ibm/cloud/cloudant/kafka/schema/ConnectRecordMapper.java:36]: this came up in testing - maybe left over from when i was looking at tombstones? anyway, it's probably useful to have

File: src/main/java/com/ibm/cloud/cloudant/kafka/schema/ConnectRecordMapper.java [hunk 2]
```diff
@@ -33,6 +33,9 @@
...
+            throw new IllegalArgumentException("Record value is null");
```
Comment (ricellis) [inline src/main/java/com/ibm/cloud/cloudant/kafka/schema/ConnectRecordMapper.java:37]: The behaviour we [describe in the README suggests](https://github.com/IBM/cloudant-kafka-connector/blob/main/README.md#sink) that we'll create an empty document for a tombstone if it isn't filtered out. So perhaps we should just return an empty Map here rather than throwing an exception?

I think we don't want to always discard tombstones because _eventually_ it would be good to actually handle deletions (somehow).

If we are going to throw here I think it ought to be a `DataException` that suggests filtering tombstones along with a README update, but I'm not really sure which is more useful behaviour.

**Review by ricellis — COMMENTED** [review]
I'm mostly ok with this, but I'm unsure on the tombstone change.
I think it should wait until after #96 is finished though.

**Review by ricellis — APPROVED** [review]
