### PR TITLE
fix: ensure collection (array/list) types are converted properly

### LINKED ISSUE #116: ConnectRecordMapper#apply doesn't support nested lists
## Environment details
- Version(s) that are affected by this issue.
    > unreleased `main`
- Java version including vendor and platform
    > 
- Apache Kafka versions (including Scala and any vendor or platform info)
    > Apache Kafka 3.2.1

### PR DESCRIPTION
**Pull request by tomblench**
fixes #116

NB original issue was incorrect, nested structs are handled (see `testConvertComplexStruct`), but collection/list/array types were not always correctly handled.

### CODE REVIEW

File: src/main/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocument.java [hunk 1]
```diff
@@ -78,38 +81,37 @@ private Map<String, Object> convertStruct(Struct struct, Map<String, Object> out
...
         return outMap;
     }
 
     // convert kafka map to map by adding key/values to passed in map, and returning it
     private Map<String, Object> convertMap(Map<?,?> inMap, Map<String, Object> outMap) {
 
+        // iterate over keys and add to map
         for (Object k : inMap.keySet()) {
             if (k instanceof String) {
                 Object v = inMap.get(k);
```
Comment (ricellis) [inline src/main/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocument.java:95]: My understanding is that it is more efficient to use the entry set if `get` needs to be called every time for the value.
```suggestion
        for (Map.Entry<?, ?> entry : inMap.entrySet()) {
            if (entry.getKey() instanceof String) {
```

File: src/main/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocument.java [hunk 2]
```diff
@@ -78,38 +81,37 @@ private Map<String, Object> convertStruct(Struct struct, Map<String, Object> out
...
-                } else if (v instanceof Struct) {
-                    outMap.put((String) k, convertStruct((Struct) v, new HashMap<>()));
-                } else {
-                    // assume that JSON serialiser knows how to deal with it
-                    outMap.put((String) k, v);
-                }
+                outMap.put((String) k, convertItem(v));
             } else {
                 throw new IllegalArgumentException("unsupported type in map key " + k.getClass());
             }
```
Comment (ricellis) [inline src/main/java/com/ibm/cloud/cloudant/kafka/mappers/SinkRecordToDocument.java:99]: counterpart of the above suggestion
```suggestion
                outMap.put((String) k, convertItem(v));
            } else {
                throw new IllegalArgumentException("unsupported type in map key " + k.getClass());
            }
```

**Review by ricellis — APPROVED** [review]
+1, one possible optimisation suggestion
